# resource_types:
#   - name: kubectl-resource
#     type: docker-image
#     source: 
#       repository: jmkarthik/concourse-kubectl-resource
#       tag: latest

resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/diwakar-k/cancourse_cicd.git
      branch: main
  - name: ecr-docker-reg
    type: docker-image
    source:
      repository: 657757981076.dkr.ecr.us-east-1.amazonaws.com/test
      aws_access_key_id: AKIAZSJLOJGKGDMNTXGJ
      aws_secret_access_key: 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
      # Name of the bucket in S3 account
      # bucket: rishi-demo
      # region_name: ap-south-1
      # filename of the application to read/write in S3 (check S3 resource documentation for parameters)
      # AWS Credentials are passed in command line on set-pipeline. Concourse can also use an external vault system to store credentials
      # aws_access_key_id: {{aws-access-key}}
      # aws_secret_access_key: {{aws-secret-key}}
      # repository: 657757981076.dkr.ecr.us-east-1.amazonaws.com/test
  # - name: repo-docker-repository
  #   type: docker-image
  #   source:
  #     email: ((docker-hub-email))
  #     username: ((docker-hub-username))
  #     password: ((docker-hub-password))
  #     repository: ((docker-hub-username))/((docker-hub-repo-name))

  # - name: kubectl
  #   type: kubectl-resource
  #   source:
  #     api_server_uri: ((server))
  #     namespace: ((namespace))
  #     certificate_authority_data: ((cad))
  #     token: ((token))

jobs:
  # - name: test
  #   public: true

  #   plan:
  #     - get: repo
  #       trigger: true
  #     - task: mvn-test
  #       file: "repo/concourse_ci/tasks/maven-test.yml"

  # - name: test
  #   public: true
  #   serial: true
  #   plan:
  #     - get: repo
  #       trigger: true
  #       # passed: [test]
  #     - task: mvn-package
  #       file: "repo/concourse_ci/tasks/maven-package.yml"
  #     - put: ecr-docker-reg
  #       params:
  #         build: repo
  #         dockerfile: repo/Dockerfile
    
  - name: package-build-and-push
    public: true
    serial: true
    plan:
      - get: repo
        trigger: true
        # passed: [test]
      - task: mvn-package-task
        file: repo/concourse_ci/tasks/maven-package.yml
      # - task: build-image-task
      #   privileged: true # oci-build-task must run in a privileged container
      #   file: repo/concourse_ci/tasks/build-image.yml
      - put: ecr-docker-reg
        params:
          build: ./repo
  # - name: deploy
  #   public: true
  #   serial: true
  #   plan:
  #     - get: repo
  #       trigger: false
  #       passed: [package]

  #     - put: kubectl
  #       params:
  #         file: "repo/spring-boot-deploy.yaml"
