platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
inputs:
  - name: repo-out
outputs:
  - name: image
params:
  CONTEXT: repo-out
run:
  path: buil