platform: linux
image_resource:
  type: registry-image
  source:
    # repository: concourse/oci-build-task
    repository: concourse/docker-image-resource
# inputs:
#   - name: repo-out
# outputs:
#   - name: image
# params:
#   CONTEXT: repo-out
run:
  path: /bin/sh
  args: ["./repo/concourse_ci/tasks/ecr.sh"]

outputs:
  - name: repo 