---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: repo

run:
  path: "mvn"
  args:
    - -f
    - repo/pom.xml
    - clean
    - package
    
outputs:
  - name: repo-out
    path: repo
